# ComputePilot
AGENT_STARTUP_DELAY = 25
INITIAL_COMPUTE_PILOT_ID = 1
DEFAULT_CORES_PER_PILOT = 1
INITIAL_SLOT_ID = 1

# DCI
QUEUEING_MEAN = 300
QUEUING_STD = 100
INITIAL_JOB_ID = 1
DEFAULT_WALLTIME = 720 # minutes = 12 hours

# ComputeUnits
INITIAL_COMPUTE_UNIT_ID = 1
DEFAULT_CORES_PER_CU = 1
